---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.23.4
    app.quarkus.io/commit-id: 67ec61d5677cd821ccc728ad942dc5b2060afd40
    app.quarkus.io/vcs-uri: https://github.com/amusa/payslip-service.git
    app.quarkus.io/build-timestamp: 2025-06-24 - 14:42:44 +0000
  labels:
    app.kubernetes.io/name: payslip-engine
    app.kubernetes.io/version: 1.1.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: payslip-engine
  namespace: payslip
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: payslip-engine
    app.kubernetes.io/version: 1.1.0-SNAPSHOT
  name: view-secrets
  namespace: payslip
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: payslip-engine
    app.kubernetes.io/version: 1.1.0-SNAPSHOT
  name: payslip-engine-view-secrets
  namespace: payslip
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: view-secrets
subjects:
  - kind: ServiceAccount
    apiGroup: ""
    name: payslip-engine
    namespace: payslip
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: payslip-engine
    app.kubernetes.io/version: 1.1.0-SNAPSHOT
  name: payslip-engine-view
  namespace: payslip
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: payslip-engine
    namespace: payslip
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.23.4
    app.quarkus.io/commit-id: 67ec61d5677cd821ccc728ad942dc5b2060afd40
    app.quarkus.io/vcs-uri: https://github.com/amusa/payslip-service.git
    app.quarkus.io/build-timestamp: 2025-06-24 - 14:42:44 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8081"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: payslip-engine
    app.kubernetes.io/version: 1.1.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: payslip-engine
  namespace: payslip
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8081
  selector:
    app.kubernetes.io/name: payslip-engine
    app.kubernetes.io/version: 1.1.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.23.4
    app.quarkus.io/commit-id: 67ec61d5677cd821ccc728ad942dc5b2060afd40
    app.quarkus.io/vcs-uri: https://github.com/amusa/payslip-service.git
    app.quarkus.io/build-timestamp: 2025-06-24 - 14:42:44 +0000
  labels:
    app.kubernetes.io/name: payslip-engine
    app.kubernetes.io/version: 1.1.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: payslip-engine
  namespace: payslip
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: payslip-engine
      app.kubernetes.io/version: 1.1.0-SNAPSHOT
  endpoints:
    - scheme: http
      targetPort: 8081
      path: /q/metrics
      interval: 10s
      honorLabels: true
