apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    #app.quarkus.io/quarkus-version: 3.23.4
    app.quarkus.io/commit-id: 67ec61d5677cd821ccc728ad942dc5b2060afd40
    app.quarkus.io/vcs-uri: https://github.com/amusa/payslip-service.git
    app.quarkus.io/build-timestamp: 2025-06-24 - 14:42:44 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8081"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: payslip-engine
    app.kubernetes.io/version: 3.0.2-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: payslip-engine
  namespace: payslip
spec:
  replicas: 1
  selector:
    matchLabels:      
      app.kubernetes.io/name: payslip-engine
      app.kubernetes.io/version: 3.0.2-SNAPSHOT
  template:
    metadata:
      annotations:
        #app.quarkus.io/quarkus-version: 3.23.4
        app.quarkus.io/commit-id: 67ec61d5677cd821ccc728ad942dc5b2060afd40
        app.quarkus.io/vcs-uri: https://github.com/amusa/payslip-service.git
        app.quarkus.io/build-timestamp: 2025-06-24 - 14:42:44 +0000
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "8081"
        prometheus.io/scheme: http
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/name: payslip-engine
        app.kubernetes.io/version: 3.0.2-SNAPSHOT        
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: docker.io/ayemi/payslip-engine:2.0
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: payslip-engine
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10      
      serviceAccountName: payslip-engine