---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sap-secret
  namespace: payslip
spec:
  encryptedData:
    SAP_PASSWORD: AgAXDBwuKPt4XoqdzwcEMeUUY7q6IWFc9cwWaSXIXuXZvDk7WxuH7NxzR5GcRKk/jbI7b7CKfwsLOinhHpKPZxbhfjyctDPbKynT8Tz6anF/8MRQbJ7Zo90FH3L9HlEBNOMBUtliVR/ivQvn88wBtl4P7kc3NObFtcYBZS8Vd3SwhlRIsFjyxHqPyC+bqQwKAin3JtFiT0CWDmIWuDCsNHenVeMg2ptXAfzuW5UoOeBGRH+0Sh0jvS0ZmTBg7wfCX8Q6AsuEws8mfpXvgj96dHIk/zAjJ3ldxiZ80jeKZyfSv73PRd2dK73DX4E3yykrButW0mEVYbnxO2N2Eyj0BJFQBJLNCC2nxPGLECR33VN6mFwluHoignXvJ2t8FZILyQ8nXBHvUNX7I4rgkHxeCvQkjXwlxdvRtspUNTqmfq/lSJtu1p50oILD91D70Afgjtx72Lbd8DJbNJ4yjv3BhpoH19zR8pIrYR3GbbF/0McI70JlbmSmKsuqIQwFeBjwlRXo9Phi+9u2O4oaeXhrBPMOLe1iysgderTAR6qBtbBpGJt7DNYqDNw2t0dYRniVGgBhgbxAxtCgJdQ6kKI/wp+DgkCT+fTBfeve1K2zoTsnhMgLMqPnCJ9YfBVUmxPR/hvoBy/IaeoglEKmGCmTbAsHE67xZ9+CEVp9rDY0ox3kNIA957yQsS2DXWtmKtM3oBX6IYkxT/BoOC9B
    SAP_USER_ID: AgAZqALhiipM1jOvAlLKIkgoch5kej5xeCfk4NChPiUHok7/gMB+4xQUOMteRCn4B6fUbRg8t7Qd1zgT/9Iqlek+se8+72jnKVhPGYQsyYgDhGYcGKjFYZ34dOH5CQnbjxMZuwY2uBWeopgHHdwkub2zGzIUQVDGcZJoSv/fF5orqE03pVkZOrsdtSY4krcZqvBlbR5YxhKY5qq54mmnCa+qYI5qkkmOU7bqw11y1COSdZwOCRWMrv7U2Oq3fPDmLtHoBjYyplaobV6x/deBQYkYHsML5v4WI82rsyCC2mzFXYOz2zOV16YUtxd8vwFljJEG7wMUZbu/yx/N6a6K0X1WrCbKlcobTU5B9agCNPb9oW/tSZoj68JJlR1N+Gn4r66UxBsSAvKUT85pTqDMalvZuu01HIaG9W4tJXAP26SlUM5UQ/N7sESf4o25r9NZAD/Z+F/xt60lo8o8Yw9cR2KtTTWvaF6O7lcNA4zHn3YyOL9aQxbxhvFtmZf8Krar5Bxgb64lo1jVCL2OD+PYO5SVx9mCLxxViX2wAb/1W19CndhypNM1hY+qhbA/7YZ3vZbka8/HS1SMv76irBsSVdss5hPtGyeUrR+UtnXq4q071btvZTxkaAA8aToluES1y0OHcDX0D2mhWJtuKG6sJipM8vBdUqcDstBOkT7eZUW+eO1K5HAX0AxNCIYUGGSRwXAWO5VV7QZlF2LZ1SE=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payslip
      name: sap-secret
      namespace: payslip
